defaults:
  - base
  - server: star04
  - algo: ipbt
  - algo/t_step@algo: '15e5'
  - algo/t_max@algo: '150e6'
  - algo/pop_size@algo: '8'
  - task: humanoid
  - search_space: rl_large
  - _self_

general:
  exp_name: '${algo.name}_${task.name_pretty}_0005'
  exp_desc: 'large space | max full trials 8 | n_init_mul 1'
  seed_base: 1723 # different seed because ablation

algo:
  n_init_mul: 1