defaults:
  - base
  - server: star04
  - algo: ipbt
  - algo/t_step@algo: '500'
  - algo/t_max@algo: '50k'
  - algo/pop_size@algo: '8'
  - task: c10
  - search_space: cls_large
  - _self_

general:
  exp_name: '${algo.name}_${task.name_pretty}_0000'
  exp_desc: 'large space | max full trials 8'
  seed_base: 1723 # different seed because ablation