defaults:
  - base
  - server: star04
  - algo: ipbt
  - algo/t_step@algo: '1500'
  - algo/t_max@algo: '150k'
  - algo/pop_size@algo: '8'
  - task: timg
  - search_space: cls_large
  - _self_

general:
  exp_name: '${algo.name}_${task.name_pretty}_0001'
  exp_desc: 'large space | max full trials 8'
  seed_base: 31153
  num_gpus: 1