defaults:
  - base
  - server: star04
  - algo: ipbt
  - algo/t_step@algo: '45e5'
  - algo/t_max@algo: '150e6'
  - algo/pop_size@algo: '8'
  - task: humanoid
  - search_space: rl_large
  - _self_

general:
  exp_name: '${algo.name}_${task.name_pretty}_0019'
  exp_desc: 'large space | max full trials 8 | step 3 percent'
  seed_base: 1723 # different seed because ablation