defaults:
  - base
  - server: star04
  - algo: asha
  - algo/t_step@algo: '15e5'
  - algo/t_max@algo: '150e6'
  - algo/pop_size@algo: '8_raytune'
  - task: humanoid_cosine_restart
  - search_space: rl_large_restart
  - _self_

general:
  exp_name: '${algo.name}_${task.name_pretty}_0001'
  exp_desc: 'large space | max full trials 8 | cosine with warm restarts'
  seed_base: 31153